<?php
$data = array (
  41 => 
  array (
    'cat_id' => '41',
    'cat_name' => '智能政企',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '41',
    'name' => '智能政企',
  ),
  50 => 
  array (
    'cat_id' => '50',
    'cat_name' => '装维工具',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '50',
    'name' => '装维工具',
  ),
  51 => 
  array (
    'cat_id' => '51',
    'cat_name' => '专享公车',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '51',
    'name' => '专享公车',
  ),
  43 => 
  array (
    'cat_id' => '43',
    'cat_name' => '智能健康',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '43',
    'name' => '智能健康',
  ),
  47 => 
  array (
    'cat_id' => '47',
    'cat_name' => '智能服务',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '47',
    'name' => '智能服务',
  ),
  44 => 
  array (
    'cat_id' => '44',
    'cat_name' => '智能家居',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '2',
    'goods_num' => '1',
    'level' => 0,
    'id' => '44',
    'name' => '智能家居',
  ),
  48 => 
  array (
    'cat_id' => '48',
    'cat_name' => 'H-ICT',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '48',
    'name' => 'H-ICT',
  ),
  49 => 
  array (
    'cat_id' => '49',
    'cat_name' => 'M-ICT',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '49',
    'name' => 'M-ICT',
  ),
  46 => 
  array (
    'cat_id' => '46',
    'cat_name' => '智能路由',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => '1',
    'level' => 0,
    'id' => '46',
    'name' => '智能路由',
  ),
  52 => 
  array (
    'cat_id' => '52',
    'cat_name' => '智能路由',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 1,
    'id' => '52',
    'name' => '智能路由',
  ),
);
?>